version: "3.9"

services:
  database: 
    image: postgres
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - ./data/:/data/postgres
 

  app:
    container_name: rentx
    image: node:14-alpine
    working_dir: /usr/src/rentx
    restart: always
    command: bash -c "yarn && yarn dev"
    ports: 
      - 3333:3333
      - 9229:9229 
    volumes: 
      - ./src/:/usr/src/rentx/src/
      - ./package.json:usr/src/rentx/package.json
    links: 
      - database
    depends_on:
      - database