version: "3"

services:
  database: 
    image: postgres
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_DB=rentx
      - POSTGRES_PASSWORD=ignite
    volumes:
      - ./data/:/data/postgres
 

  app:
    container_name: rentx
    image: node:14
    working_dir: /usr/src/rentx
    restart: always
    command: bash -c "yarn && yarn dev"
    ports: 
      - 3333:3333
      - 9229:9229 
    volumes: 
      - .:/usr/src/rentx
      - /usr/src/rentx/node_modules
      - ./package.json:/usr/src/rentx/package.json
    links: 
      - database
    depends_on:
      - database